
GET http://localhost:3000/sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc3NzI0MTU5MSwiZXhwIjoxNzc3MjQ1MTkxfQ.wsueWZiP6aR86K_-sSdSu5CMYEUrQea9ktPN0cnTgLc